### ISSUE TITLE
Add documentation of symbols TODO for phase 2

### ISSUE THREAD

**Issue by Plavit** [Military-Tactical-Graphics/milsymbol-generator#11]

**Comment by ondrej-podolsky** [comment]
Comleted. I created simple wiki page for Stage 2 [To display here.](https://github.com/Military-Tactical-Graphics/milsymbol-generator/wiki/Progress-of-stage-2)

**Comment by ondrej-podolsky** [comment]
Completed. I created simple wiki page for Stage 2 [To display here](https://github.com/Military-Tactical-Graphics/milsymbol-generator/wiki/Progress-of-stage-2).
