### ISSUE TITLE
Research specific SIDC and specification of the "Forward Line of Own Troops" (FLOT)

### ISSUE THREAD

**Issue by Plavit** [Military-Tactical-Graphics/milsymbol-generator#9]

**Comment by Plavit** [comment]
For reference:
![image](https://user-images.githubusercontent.com/22589593/105888037-bb1c4c00-600c-11eb-8e8f-e0ae9929a600.png)

**Comment by ondrej-podolsky** [comment]
SIDC found in the NATO MIL-STD-2525C Standard - G*GPGLF---****X
 
Parameters:
1. Anchor Points. This graphic requires at least
two points, points 1 and 2, to define the line.
Additional points can be defined to extend the
line .
2. Size/Shape. The first and last anchor points
determine the length of the line. The end-of line
information will typically be posted at the ends
of the line as it is displayed on the screen.
3. Orientation. Orientation is determined by the
order in which the anchor points are entered.

![flot](https://user-images.githubusercontent.com/74501337/106167608-aa471400-618d-11eb-8f61-33624b570520.png)
